config/routes.rb
Rails.application.routes.draw do
  get 'search/search'
  devise_for :users
  root to: 'homes#top'
  get 'home/about' => 'homes#about'

  get '/search', to: 'search#search'

    resources :users do
      get :followings, on: :member
      get :followers, on: :member
    end

  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  # post 'follow/:id' => 'relationships#follow', as: 'follow'
  # post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'

  resources :relationships, only: [:create, :destroy]

end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def search
    @book_or_user = params[:option]
    @how_search = params[:choice]
    @search = params[:search]

    if @book_or_user == "1"
      @books = Book.search(params[:search], @book_or_user, @how_search)
    else
      @users = User.search(params[:search], @book_or_user, @how_search)
    end
    #binding.pry
    
    # @model = params["search"]["model"]
    # @content = params["search"]["content"]
    # @method = params["search"]["method"]
    # @records = search_for(@model,@content, @method).page(params[:page]).per(5)
  end

  # private
  # def search_for(model,content,method)
  #   if model == 'book'
  #     method == 'partial'
  #     Book.where('family_name LIKE ?', '%'+content+'%')
  #   else
  #     method == 'partial'
  #     User.where('name LIKE ?', '%'+content+'%')
  #   end
  # end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/_form.html.erb
<%= form_tag(search_path, :method => 'get') do %>
  <%= text_field_tag :search %>
  <%= select_tag(:option, options_for_select([["Book", "1"],["User", "2"]])) %>
  <%= select_tag(:choice, options_for_select([["部分一致", "1"],["完全一致", "2"],["前方一致", "3"],["後方一致", "4"]])) %>
  <%# hidden_field_tag 'search[method]', "部分一致" => "partial" %>
  <%= submit_tag '検索', :name => nil %>
<% end %>

app/views/search/search.html.erb
<% if @book_or_user == "1" %>
  <div class="col-md-8 offset-md-1">
    <h2>
      Books search for
      <%= @search %>
      </h2>
    <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
      <% @books.each do |book| %>
        <tr>
          <td>
            <%= link_to user_path(book.id) do %>
              <%= attachment_image_tag book.user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size:"40x40" %>
            <% end %>
          </td>
          <td><%= link_to book.title,  book_path(book.id) %></td>
          <td><%= book.body %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>

<% elsif @book_or_user == "2" %>
<div class="col-md-8 offset-md-1">
  <h2>
    Users search for
    <%= @search %>
    </h2>
  <table class="table">
    <thead>
      <tr>
        <th>image</th>
        <th>name</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size:'40x40' %></td>
        <td><%= user.name %></td>
        <td><%= "フォロー数: #{user.followings.count}" %></td>
        <td><%= "フォロワー数: #{user.followers.count}" %></td>
        <td>
          <%= render "relationships/follow", user: user %>
        </td>
        <td><%= link_to "Show", user_path(user.id) %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>
<% else %>
<% end %>