config/routes.rb
Rails.application.routes.draw do
  get 'search/search'
  devise_for :users
  root to: 'homes#top'
  get 'home/about' => 'homes#about'

  get '/search', to: 'search#search'

    resources :users do
      get :followings, on: :member
      get :followers, on: :member
    end

  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  # post 'follow/:id' => 'relationships#follow', as: 'follow'
  # post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'

  resources :relationships, only: [:create, :destroy]

end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    @user = @book.user
    @comment = current_user.book_comments.new(book_comment_params)
    @comment.book_id = @book.id
    @comment.save
    #redirect_to book_path(book)
  end

  def destroy
    @book = Book.find(params[:book_id])
    @comment = BookComment.find(params[:id])
    #BookComment.find_by(id:params[:id],book_id:params[:book_id]).destroy
    @comment.destroy
    #redirect_to book_path(params[:book_id])
    @user = @book.user
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/views/book_comments/_form.html.erb
<%= form_with(model:[book,book_comment]) do |f| %>
  <%= f.text_area:comment, rows:'5', class:"form-control book_comment" %>
  <%= f.submit "送信" %>
<% end %>

app/views/book_comments/_index.html.erb
<% book.book_comments.each do |book_comment| %>
  <tr>
    <td>
      <%= link_to user_path(book_comment.user.id), method: :get do %>
        <%= attachment_image_tag user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %> <br>
        <%= book_comment.user.name %>
      <% end %>
    </td>
    <td><%= book_comment.comment %></td>
    <td>
      <% if current_user == book_comment.user %>
        <%= link_to book_book_comment_path(book_comment.book_id,book_comment.id), class:"btn btn-sm btn-danger", method: :delete, remote: true do %>
          Destroy
        <% end %>
      <% end %>
    </td>
  </tr>
<% end %>

app/views/book_comments/create.js.erb
$(".comments_area-").html("<%= j(render 'book_comments/index', user: @user, book: @book) %>");
$("textarea").val('');

app/views/book_comments/destroy.js.erb
$(".comments_area-").html("<%= j(render 'book_comments/index', user: @user, book: @book) %>");
$("textarea").val('');