config/routes.rb
Rails.application.routes.draw do
  get 'search/search'
  devise_for :users
  root to: 'homes#top'
  get 'home/about' => 'homes#about'

  get '/search', to: 'search#search'

    resources :users do
      get :followings, on: :member
      get :followers, on: :member
    end

  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  # post 'follow/:id' => 'relationships#follow', as: 'follow'
  # post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'

  resources :relationships, only: [:create, :destroy]

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

 before_action :set_user

  def create
    following = current_user.follow(@user)
    if following.save
      flash[:success] = 'ユーザーをフォローしました'
      redirect_to request.referer
    else
      flash.now[:alert] = 'ユーザーのフォローに失敗しました'
      redirect_to @user
    end
  end

  def destroy
    following = current_user.unfollow(@user)
    if following.destroy
      flash[:success] = 'ユーザーのフォローを解除しました'
      redirect_to request.referer
    else
      flash.now[:alert] = 'ユーザーのフォロー解除に失敗しました'
      redirect_to @user
    end
  end

  private
  def set_user
    @user = User.find(params[:relationship][:follow_id])
  end

end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_follow.html.erb
<% unless user == current_user %>
  <% if current_user.following?(user) %>
  <% @relationship = current_user.relationships.find_by(followed_id: user.id) %>
    <%= form_with model: @relationship, url: relationship_path(@relationship.id), method: :delete, local:true do |f| %>
      <%= f.hidden_field :follow_id, value: user.id %>
      <%= f.submit 'フォロー外す', class:"btn btn-success" %>
    <% end %>
  <% else %>
    <%= form_with model: current_user.relationships.build, url: relationships_path, local:true do |f| %>
      <%= f.hidden_field :follow_id, value: user.id %>
      <%= f.submit 'フォローする', class:"btn btn-success" %>
    <% end %>
  <% end %>
<% end %>