config/routes.rb
Rails.application.routes.draw do
  get 'search/search'
  devise_for :users
  root to: 'homes#top'
  get 'home/about' => 'homes#about'

  get '/search', to: 'search#search'

    resources :users do
      get :followings, on: :member
      get :followers, on: :member
    end

  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  # post 'follow/:id' => 'relationships#follow', as: 'follow'
  # post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'

  resources :relationships, only: [:create, :destroy]

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  # has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # has_many :following_user, through: :follower, source: :followed
  # has_many :follower_user, through: :followed, source: :follower
  # has_many :followings, through: :relationships, source: :follow
  # has_many :followers, through: :passive_ralationships, source: :user

  has_many :relationships, foreign_key: "follower_id"
  has_many :followings, through: :relationships, source: :followed

  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id"
  has_many :followers, through: :reverse_of_relationships, source: :follower

  validates :name, length: { in: 2..20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(followed_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(followed_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end

  def User.search(search, book_or_user, how_search)
    if book_or_user == "2"
      if how_search == "1"
        User.where(['name LIKE ?', "%#{search}%"])
      elsif how_search == "2"
        User.where(['name LIKE ?', "#{search}"])
      elsif how_search == "3"
        User.where(['name LIKE ?', "#{search}%"])
      elsif how_search == "4"
        User.where(['name LIKE ?', "%#{search}"])
      else
        User.all
      end
    end
  end

  include JpPrefecture
  jp_prefecture :prefecture_code

  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books.page(params[:page]).reverse_order
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render "edit"
    else
      redirect_to user_path(current_user.id)
    end
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path, notice: 'You have created book successfully'
    else
      render :show
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: 'You have updated user successfully'
    else
      render :edit
    end
  end

  def followings
    @user = User.find(params[:id])
    @users = @user.followings.all
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.followers.all
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user.html.erb
<h2>User info</h2>
<%= attachment_image_tag user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg", size:"100x100" %>
<table class = "table">
  <tbody>
    <tr><th>name</th><td><%= user.name %></td></tr>
    <tr><th>introduction</th><td><%= user.introduction %></td></tr>
    <tr>
      <th>follows</th>
      <td>
          <%= link_to user.followings.count, followings_user_path(user.id) %>
      </td>
    </tr>
    <tr>
      <th>followers</th>
      <td><%= link_to user.followers.count, followers_user_path(user.id) %></td>
    </tr>
  </tbody>
</table>
<% if user == current_user %>
  <div class="row">
    <%= link_to edit_user_path(user.id), class: "btn btn-outline-secondary btn-block", method: :get do %>
    <i class="fas fa-user-cog"></i>
    <% end %>
  </div>
<%end %>

app/views/users/edit.html.erb
<p class="text-success">
  <% notice %>
</p>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@user.errors.count, "error") %>
      prohibited this book from being saved:
    </h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 cpl-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <%= form_with model:@user, local:true do |f| %>
        <div class="form-group">
          <label for="user_name">Name</label><br>
          <%= f.text_field :name, autofocus: true, class:"form-control" %>
        </div>
        <div class="form-group">
          <label for="user_image">Image</label><br>
          <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
        </div>
        <div class="form-group">
          <label for="user_introduction">Introduction</label><br>
          <%= f.text_area :introduction, class:"form-control" %>
        </div>
        <div class="form-group">
          <%= f.submit 'Update User', class:"btn btn-secondary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/followers.html.erb
<div class="col-md-8 offset-md-1">
  <h2>Follower Users</h2>
  <table class="table">
    <thead>
      <tr>
        <th>image</th>
        <th>name</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
    <% @user.followers.each do |user| %>
      <tr>
        <td><%= attachment_image_tag user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size:'40x40' %></td>
        <td><%= user.name %></td>
        <td><%= "フォロー数: #{user.followings.count}" %></td>
        <td><%= "フォロワー数: #{user.followers.count}" %></td>
        <td><%= link_to "Show", user_path(user.id) %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/users/followings.html.erb
<div class="col-md-8 offset-md-1">
  <h2>Follow Users</h2>
  <table class="table">
    <thead>
      <tr>
        <th>image</th>
        <th>name</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
    <% @user.followings.each do |user| %>
      <tr>
        <td><%= attachment_image_tag user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size:'40x40' %></td>
        <td><%= user.name %></td>
        <td><%= "フォロー数: #{user.followings.count}" %></td>
        <td><%= "フォロワー数: #{user.followers.count}" %></td>
        <td><%= link_to "Show", user_path(user.id) %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/users/index.html.erb
<p class="text-success">
  <%= notice %>
</p>
<div class = "container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/user', user: current_user %>
      <%= render 'books/book', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= attachment_image_tag user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size:'40x40' %></td>
            <td><%= user.name %></td>
            <td><%= "フォロー数: #{user.followings.count}" %></td>
            <td><%= "フォロワー数: #{user.followers.count}" %></td>
            <td>
              <%= render "relationships/follow", user: user %>
            </td>
            <td><%= link_to "Show", user_path(user.id) %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<p class="text-success">
  <%= notice %>
</p>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@user.errors.count, "error") %>
      prohibited this obj from being saved:
    </h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div class = "container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/user', user: @user %>
      <div class="form-group">
        <%= render "relationships/follow", user: @user %>
      </div>
      <%= render 'books/book', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
        <% @user.books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(@user.id) do %>
              <%= attachment_image_tag @user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size:"40x40" %>
              <% end %>
              </td>
            <td><%= link_to book.title, book_path(book.id) %></td>
            <td><%= book.body %></td>
          </tr>
        <% end %>
        <% paginate @books %>
        </tbody>
      </table>
    </div>
  </div>
</div>